name: Rust

on:
  push:
    paths: 
      - "dev-backend/**"
  pull_request:
    paths:
      - "dev-backend/**"
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Build (Offline Mode)
      run: | 
        cd dev-backend
        cargo build --offline --verbose
        
    - name: Run tests
      run: |
        cd dev-backend
        cargo test --verbose
